
import arunachal from "../Assets/Map/arunachal_pradesh.jpg"
import nagaland from "../Assets/Map/nagaland.jpg"
import odisha from "../Assets/Map/odisha.png"
import punjab from "../Assets/Map/PUNJAB.jpg"
import andhra from "../Assets/Map/andhra.jpg"
import assam from "../Assets/Map/Assam Map.jpg"
import bihar from "../Assets/Map/Bihar Map.jpg"
import chandigarh from "../Assets/Map/Chandigarh .jpg";
import chhattisgarh from "../Assets/Map/Chhattisgarh Map.jpg"
import Dadra  from "../Assets/Map/Dadra.jpg"
import delhi from "../Assets/Map/Delhi .jpg"
import Gujarat from "../Assets/Map/Gujarat .jpg"
import haryana from "../Assets/Map/Haryana.jpg"
import himachal from "../Assets/Map/Himachal Pradesh .jpg"
import jharkhand from "../Assets/Map/Jharkhand .jpg"
import jm from "../Assets/Map/Jm.jpg"
import kerala from "../Assets/Map/Kerala .jpg"
import laksh from "../Assets/Map/Lakshadweep .jpg"
import madhya from "../Assets/Map/Madhya Pradesh .jpg"
import maharashtra from "../Assets/Map/Maharashtra.jpg"
import manipur from "../Assets/Map/Manipur.jpg"
import meghalaya from "../Assets/Map/Meghalaya.jpg"
import mizoram from "../Assets/Map/Mizoram.jpg"
import rajasthan from "../Assets/Map/Rajasthan .jpg"
import sikkim from "../Assets/Map/Sikkim .jpg"
import tamil from "../Assets/Map/Tamil Nadu.jpg"
import telangana from "../Assets/Map/Telangana.jpg"
import tripura from "../Assets/Map/Tripura .jpg"
import uttar from "../Assets/Map/Uttar Pradesh .jpg"
import uttarakhand from "../Assets/Map/Uttarakhand .jpg"
import west from "../Assets/Map/West Bengal .jpg"
import karnataka from "../Assets/Map/karnataka.jpg"
import andaman  from "../Assets/Map/andaman.jpg"
const stateInfo = [
 {
    id: 'IN-AN',
 layout:andaman,
    state_info:"The Andaman and Nicobar Islands is a Union Territory of India, consisting of 572 islands, of which only about 37 are inhabited. Located at the junction of the Bay of Bengal and the Andaman Sea, the islands are renowned for their pristine natural beauty, diverse ecosystems, and vibrant cultural heritage"
 },

    
 {
    id: "IN-LD",
    layout:laksh,
    state_info:"The Lakshadweep Islands is a Union Territory of India, consisting of 36 small islands, located in the Arabian Sea. Known for its stunning coral reefs, lush greenery, and pristine beaches, it is India's smallest Union Territory in terms of both area and population.Longitude: 71° to 74° EastTotal Area: 32 square kilometersIsland Groups:Lakshadweep comprises 36 islands, including atolls, reefs, and submerged banks, of which only 10 are inhabitedCapital:Kavaratti"

 },

 {
    id: "IN-AS",
    layout:assam,
    state_info:"Assam is a state in northeastern India, south of the eastern Himalayas along the Brahmaputra and Barak River valleys. Assam covers an area of 78,438 km2 (30,285 sq mi). It is the second largest state in northeastern India by area and the largest in terms of population, with more than 31 million inhabitants. The state is bordered by Bhutan and Arunachal Pradesh to the north; Nagaland and Manipur to the east; Meghalaya, Tripura, Mizoram and Bangladesh to the south; and West Bengal to the west via the Siliguri Corridor, a 22-kilometre-wide (14 mi) strip of land that connects the state to the rest of India. Assamese and Boro are the official languages of Assam. Meitei (Manipuri) is recognised as an additional official language[14] in Hojai district and for the Barak Valley region, alongside Bengali, which is also an official language in the Barak Valley."
 },

 {
    id: "IN-AR",
    layout:arunachal,
    state_info:"Arunachal Pradesh is a state in northeast India. It was formed from the North-East Frontier Agency (NEFA) region, and India declared it as a state on 20 February 1987. Itanagar is its capital and largest town. It borders the Indian states of Assam and Nagaland to the south. It shares international borders with Bhutan in the west, Myanmar in the east, and a disputed 1,129 km border with China's Tibet Autonomous Region in the north at the McMahon Line.[21] Arunachal Pradesh is claimed by China as South Tibet as part of the Tibet Autonomous Region;[22] China occupied some regions of Arunachal Pradesh in 1962 but later withdrew its forces.[23][24]s of the 2011 Census of India, Arunachal Pradesh has a population of 1,383,727 and an area of 83,743 square kilometres (32,333 sq mi). With only 17 inhabitants per square kilometre, it is the least densely populated state of India. It is an ethnically diverse state, with predominantly Monpa people in the west, Tani people in the centre, Mishmi and Tai people in the east, and Naga people in the southeast of the state. About 23 major tribes and 100 sub-tribes live in the state,[citation needed] including Nocte, Adi, Nyishi, Singpho, Galo, Tagin, Apatani. The Nyishi are the largest ethnic group in the region. The Mishmi tribe has three sub-tribes, namely Idu-Mishmi, Digaru-Mishmi and Miju-Mishmi"
 },

 {
    id: "IN-WB",
    layout:west,
    state_info:"The history of West Bengal basically refers to the history of the western part of Bengal, located in the eastern part of the Indian subcontinent. Evidence of human settlement has been found in West Bengal about 42,000 years ago. The presence of human settlement of that period has been found in the Ayodhya Hills of West Bengal.[1][2][3] By 2,000 BCE, settled life had increasingly spread of human civilization in the Damodar-Ajay River Valley, which was contemporary with the Harappa-Mahenjodaro civilization.[4][5] The southern part of West Bengal witnessed the presence of the Vanga Kingdom between 1100 BCE and 350 BCE, which was contemporary with the Vedic civilization of northern India.[5]Among the Mahajanapadas, Magadha became powerful around 350 BCE, at that time rulers of the Nanda dynasty of Magadha incorporated the territory ofWest Bengal into their empire. West Bengal was under the rule of all Magadha-centric empires after the Nanda Empire. Tamralipta in West Bengal was the main seaport of the Magadha-centered Maurya Empire.[6] Most of the West Bengal's territory was ruled under the Gupta Empire, that arose in northern India after the collapse of the Magadha-centric empires.In Bengal, the Gaur kingdom was established in 690 AD, which spread across West Bengal and present-day Bangladesh. Gaur is often referred to as the first well-established independent political entity in Bengal.[7] After this kingdom, the Pala Empire in 750 AD and the Sena Empire in 1070 AD respectively emerged across West Bengal. Both of these empires were mainly Bengal-centric.Islamic conquests were established in West Bengal as early as the 13th century. At this time Bengal along with West Bengal was included in the Ghaznavid Empire. West Bengal was ruled under the Delhi Sultanate from the 13th to the 14th century and the Bengal Sultanate from the 14th to the 16th century. In the 16th century, after the fall of the Bengal Sultanate, West Bengal came under the Mughal Empire.Murshidabad in West Bengal was the capital of independent Nawab Bengal (1717–1765). In 1765, the British took over the control of Bengal including West Bengal from the Nawabs of Bengal.[8] The Bengal Presidency of the British Indian Empire was divided into West Bengal and East Bengal in August 1947; West Bengal was included in the Dominion of India and gained independence as an Indian state."
 },

 {
    id: "IN-NL",
    layout:nagaland,
    state_info:"Nagaland is a state in the north-eastern region of Indi. It is bordered by the Indian states of Arunachal Pradesh to the north, Assam to the west, Manipur to the south, and the Naga Self-Administered Zone of the Sagaing Region of Myanmar (Burma) to the east. Its capital city is Kohima and its largest city is the twin Chümoukedima–Dimapur. The state has an area of 16,579 square kilometres (6,401 sq mi) with a population of 1,980,602 as per the 2011 Census of India, making it one of the smallest states of India.Nagaland has a largely monsoon climate with high humidity levels. Annual rainfall averages around 1,800–2,500 millimetres (70–100 in), concentrated in the months of May to September. Temperatures range from 21 to 40 °C (70 to 104 °F). In winter, temperatures do not generally drop below 4 °C (39 °F), but frost is common at high elevations. Summer is the shortest season in the state, lasting only a few months. The temperature during the summer season remains between 16 and 31 °C (61 and 88 °F). Winter often arrives early, with bitter cold and dry weather striking certain regions of the state. The maximum average temperature recorded in the winter season is 24 °C (75 °F). Strong northwest winds blow across the state during the months of February and March."
 },

 {
    id: "IN-MN",
    layout:manipur,
    state_info:"Manipur, located in the northeastern part of India, is a state known for its stunning landscapes, rich culture, and historical significance. Covering an area of 22,327 square kilometers, Manipur is bordered by Nagaland to the north, Mizoram to the south, Assam to the west, and Myanmar (Burma) to the east. The state is often referred to as the Switzerland of India due to its picturesque landscapes, including lush green hills, valleys, and rivers. Imphal, the capital city, is the largest urban center and the political and cultural heart of the state.Manipur has a diverse cultural heritage, influenced by various indigenous communities. The majority of the population belongs to the Meitei ethnic group, who predominantly follow Hinduism, while a significant number of tribal groups, including Nagas and Kukis, practice Christianity and indigenous faiths. The state is known for its traditional arts, including dance forms like Manipuri dance, which is a classical dance style that has been recognized internationally. The famous festival of Lai Haraoba, celebrated by the Meitei people, is an important cultural event that honors the gods and celebrates traditional customs.The state’s economy is mainly agrarian, with agriculture being the primary occupation of the people. Rice is the staple food, and crops like maize, pulses, vegetables, and fruits are widely cultivated. Manipur also has a growing handloom and handicraft industry, with products like Manipuri shawls, bamboo crafts, and pottery being highly valued. While agriculture forms the backbone of the state’s economy, tourism also plays a significant role due to its natural beauty, cultural diversity, and historical landmarks."
 },

 {
    id: "IN-MZ",
    layout:mizoram,
    state_info:"Mizoram is a state situated on the extreme south of northeastern India, it is a land of unending natural beauty with a variety of flora and fauna. The word Mizo means highlander Mizoram is located between 21-58o to 24o 29' north latitude and 92o 29' to 93o 22' east longitude. The tropic of Cancer passes near the capital, Aizawl town. Mizoram occupies the north east corner of India. It is bounded on the north by the state of Assam and the state of Manipur, on the east and south by Chin Hills and Arakan (Myanmar), and on the west by the Chittagong hill tracts of Bangladesh and the state of Tripura. Mizoram borders three states of India - Assam, Manipur and Tripura. Its geographical borders with Assam, Manipur and Tripura extended over 123 km, 95 km and 66 km, respectively. Mizoram is a land of hills. The hills run in ridges from north to south. They have an average height of 900 meters, the highest point being the Blue Mountain After independence of India, Mizoram continued to be part of Assam. The district was carved out of Assam under the reorganization act of 1971 raised to the status of a union territory on January 21, 1972. In 1987, Mizoram became the 23rd full-fledged state of the country."
 },

 {
    id: "IN-TR",
    layout:tripura,
    state_info:"Tripura (/ˈtrɪpʊrə, -ərə/)[10] is a state in northeastern India. The third-smallest state in the country, it covers 10,491 km2 (4,051 sq mi); and the seventh-least populous state with a population of 3.67 million.[11] It is bordered by Assam and Mizoram to the east and by Bangladesh to the north, south and west.[12] Tripura is divided into 8 districts and 23 sub-divisions, where Agartala is the capital and the largest city in the state. Tripura has 19 different tribal communities[13] with a majority Bengali population. Bengali, English and Kokborok are the state's official languages.[7]The area of modern Tripura — ruled for several centuries by the Manikya Dynasty — was part of the Tripuri Kingdom (also known as Hill Tippera). It became a princely state under the British Raj during its tenure, and acceded to independent India in 1947. It merged with India in 1949 and was designated as a 'Part C State' (union territory).[14] It became a full-fledged state of India in 1972.Tripura lies in a geographically isolated location in India, as only one major highway, National Highway 8, connects it with the rest of the country. Five mountain ranges — Baramura, Atharamura, Longtharai, Shakhan and Jampui Hills — run north to south, with intervening valleys; Agartala, the capital, is located on a plain to the west. The state has a tropical savanna climate, and receives seasonal heavy rains from the south west monsoon.Forests cover more than half of the area, in which bamboo and cane tracts are common. Tripura has the highest number of primate species found in any Indian state. Due to its geographical isolation, economic progress in the state is hindered. Poverty and unemployment continue to plague Tripura, which has a limited infrastructure. Most residents are involved in agriculture and allied activities, although the service sector is the largest contributor to the state's gross domestic product.According to the 2011 census, Tripura is one of the most literate states in India, with a literacy rate of 87.75%. Mainstream Indian cultural elements coexist with traditional practices of the ethnic groups, such as various dances to celebrate religious occasions, weddings and festivities; the use of locally crafted musical instruments and clothes; and the worship of regional deities. The sculptures at the archaeological sites Unakoti, Pilak and Devtamura provide historical evidence of artistic fusion between organised and indigenous religions."
 },

 {
    id: "IN-ML",
    layout:meghalaya,
    state_info:" Meghalaya, meaning abode of clouds is a northeastern state of India known for its scenic beauty, diverse tribal culture, and rich heritage. It shares borders with Assam and Bangladesh and is known for its picturesque landscapes, including rolling hills, vast forests, waterfalls, and caves. The state is the wettest region of India, with the wettest areas in the southern Khasi Hills recording an average of 12,000 mm (470 in) of rain a year. English is official language of Meghalaya It extends for about 300 kilometres in length and about 100 kilometres in breadth. The capital of Meghalaya is Shillong. About 70 per cent of the state is forested. The Meghalaya subtropical forests ecoregion encompasses Meghalaya has predominantly an agrarian economy with a significant commercial forestry industry. The important crops are potatoes, rice, maize, pineapples, bananas, papayas, and spices. The service sector is made up of real estate and insurance companies.  The state is geologically rich in minerals, but it has no significant industries. The state has about 1,170 km (730 mi) of national highways. It is also a major logistical center for trade with Bangladesh. A theory for the origin of rice is by Ian Glover while states, India is centof greatest diversity of domesticated rice with over 20,000 identified species and Northeast India is the most favorable single area of the origin of domesticated rice. The limited archaeology done in the hills of Meghalaya suggest human settlement since ancient times.  Meghalaya is one of the Seven Sister States of northeast India. The state of Meghalaya is mountainous, with stretches of valley and highland plateaus, and it is geologically rich. It consists mainly of Archean rock formations. These rock formations contain rich deposits coal, limestone, uranium and sillimanite. of valuable minerals like The name Meghalaya was given by Shiba P. Chatterjee, a geography professor at the University of Calcutta. "
 },

 {
    id: "IN-SK",
    layout:sikkim,
    state_info:"Sikkim  is a state in northeastern India. It borders the Tibet Autonomous Region of China in the north and northeast, Bhutan in the east, Koshi Province of Nepal in the west, and West Bengal in the south. Sikkim is also close to the Siliguri Corridor, which borders Bangladesh. Sikkim is the least populous and second-smallest among the Indian states. Situated in the Eastern Himalaya, Sikkim is notable for its biodiversity, including alpine and subtropical climates, as well as being a host to Kangchenjunga, the highest peak in India and third-highest on Earth. Sikkim's capital and largest city is Gangtok. Almost 35% of the state is covered by Khangchendzonga National Park – a UNESCO World Heritage Site.  The Kingdom of Sikkim was founded by the Namgyal dynasty in the 17th century. It was ruled  Buddhist priest-kings known as the Chogyal. It became a princely state of the British Indian Empire in 1890. Following Indian independence, Sikkim continued its protectorate status withthe Union of India after 1947 and the Republic of India after 1950. It enjoyed the highest literacy rate and per capita income among Himalayan states. In 1973, anti-royalist riots took place in front of the Chogyal's palace. In 1975, after the Indian Army took over the city of Gangtok, a referendum was held that led to the dissolution of the monarchy and Sikkim joining India as its 22nd state.  Modern Sikkim is a multiethnic and multilingual Indian state. The official languages of the state are English, Nepali, Bhutia, and Lepcha. Additional official languages include Gurung, Limbu, Magar, Mukhia, Newari, Rai, Sherpa and Tamang for the purpose of preservation of culture and tradition in the state. English is taught in schools and used in government documents. The predominant religion is Hinduism, with a significant Vajrayana Buddhist minority. Sikkim's economy is largely dependent on agriculture and tourism. As of 2019, the state had the fifthsmallest GDP among Indian states, although it is also among the fastest-growing"
 },

 
 {
    id: "IN-KL",
    layout:kerala,
    state_info:"Kerala, known as “God’s Own Country,” is a land rich in history and culture. This enchanting state on India’s southwestern coast is renowned for its diverse heritage that spans millennia. From ancient civilizations and powerful dynasties to colonial influences and post-independence progress, Kerala’s history and culture are a fascinating blend of tradition and modernity. The state’s vibrant festivals, classical arts, and unique architecture further highlight its cultural richness, making Kerala a captivating destination for those seeking to explore its storied past and dynamic present.Kerala’s ancient and medieval history is a captivating journey through time, marked by the rise of powerful dynasties and the flourishing of early civilizations. This period saw the establishment of significant cultural and political foundations that have shaped Kerala’s unique identity. The influence of various dynasties and the growth of trade and literature during this era laid the groundwork for Kerala’s enduring legacy in history and culture.Kerala’s early civilizations and dynasties played a crucial role in shaping its rich history and culture. The Chera dynasty, one of the prominent ruling powers, was instrumental in establishing Kerala as a major trade hub during the Sangam period. This era saw extensive maritime trade with distant lands like Rome and China, fostering a vibrant exchange of goods, ideas, and cultural practices. The contributions of these early civilizations and dynasties laid the foundation for Kerala’s unique cultural heritage."
 },
 
 {
    
    id: "IN-TN",
    layout:tamil,
    state_info:"The State of Tamil Nadu has a hoary antiquity. Though early sangam classics throw historical references, we pass to recorded history only from the Pallavas. he southern states of India were under the hegemony of the Cholas, the Cheras and the Pandyas for centuries. The Pallavas held supremacy from about the second quarter of the fourth century A.D. They were the originators of the famous Dravidian style of temple architecture. The last Pallava ruler was Aparajita, in whose reign the later Cholas under Vijayalaya and Aditya asserted themselves by about the 10th century. At the end of the 11th century, Tamil Nadu was ruled by several dynasties like the Chalukyas, Cholas and Pandyas. In the two centuries that followed, the imperial Cholas gained paramountcy over South India. Muslims gradually strengthened their position, which led to the establishment of the Bahamani Sultanate, by the middle of the 14th century. At the same time, the Vijayanagar Kingdom quickly consolidated itself and extended its sway over the whole of South India, and at the close of the century, Vijayanagar became the supreme power in South. However, it crumbled at the battle of Talikota in 1564 to the confederate forces of the Deccan Sultans. Even during the period of the tumultuous confusion that followed the battle of Talikota, European commercial interest had appeared as rivals in the area of South India. The Portuguese, the Dutch, the French and the English came in quick succession and established trading centres known as 'Factories'. East India Company, which had established its factory at Masulipatnam (now in Andhra Pradesh) in 1611, gradually annexed territories by encouraging enmity among the native rulers. Tamil Nadu was one of the first of British settlements in India. The State is the successor to the old Madras Presidency, which covered the bulk of the southern peninsula in 1901. The composite Madras State was later reorganised, and the present Tamil Nadu was formed. Tamil Nadu is bounded on north by Andhra Pradesh and Karnataka, on the west by Kerala, on the east by the Bay of Bengal, and on the south by the Indian Ocean. "
 },
 
 {
    id: "IN-AP",
    layout:andhra,
    state_info:"Andhra Pradesh is a state in the southern coastal region of India. It is the seventh-largest state and the tenth-most populous in the country. Telugu, one of India's classical languages, is the primary official language and the most widely spoken language. Amaravati is the state capital, while the largest city is Visakhapatnam. The state shares borders with Telangana to the northwest, Odisha to the northeast, Chhattisgarh to the north, Karnataka to the southwest, Tamil Nadu to the south, and the Bay of Bengal to the southeast. It has the second-longest coastline in India at about 974 km (605 mi).Andhra Pradesh is the seventh-largest state with an area of 162,970 km2 (62,920 sq mi).[3] Politically, the state shares borders with Telangana to the northwest, Orissa to the northeast, Chhattisgarh to the north, Karnataka to the southwest, Tamil Nadu to the south, and the Bay of Bengal to the southeast. Yanam district, an enclave of Puducherry, is in the state bordering Kakinada district.[77] It has a coastline of around 974 kilometres (605 mi), which makes it the second-longest coastline in the nation.[3]In South India coming of age, the ceremony is celebrated when a girl reaches puberty. For the ceremony, the girl wears a Langa Voni given by her maternal grandparents during the first part of the ceremony. For the second part of the ceremony, she wears a saree given by her paternal grandparents. This marks her transition into womanhood."
 },
 
 {
    id: "IN-PY",
    layout:nagaland,
    state_info:"Puducherry, formerly known as Pondicherry, is a Union Territory of India, renowned for its colonial charm, serene beaches, and spiritual ambiance. Covering an area of 483 square kilometers, Puducherry consists of four geographically distinct regions: Puducherry and Karaikal on the east coast near Tamil Nadu, Yanam in Andhra Pradesh, and Mahe on the west coast in Kerala. Puducherry town serves as the administrative capital, and the region features a coastline along the Bay of Bengal and the Arabian Sea.Historically, Puducherry has been influenced by various South Indian dynasties, including the Cholas and Pallavas. Its modern history began with the arrival of the French in 1674, who ruled the region until 1954. Other European powers, such as the Dutch and British, also briefly controlled parts of the area. Puducherry officially became a part of India on November 1, 1954, following a referendum, and was designated as a Union Territory in 1963.The culture of Puducherry is a fascinating blend of French and Indian traditions. The region’s population, approximately 1.25 million, speaks languages like Tamil, Telugu, Malayalam, and French, with English widely used in administration and tourism. Predominantly Hindu, the region also has significant Christian and Muslim communities. French influence is evident in the architecture, street names, cuisine, and festivals. Events like Bastille Day, alongside local festivals such as Pongal and Masi Magam, showcase the unique cultural amalgamation."
 },
 
 {
    id: "IN-TG",
    layout:telangana,
    state_info:"Telangana region has been ruled by great dynasties such as Sathavahanas, Kakatiyas, Chalukyas, Mughals, Qutubshahis, Asafjahis. Kakathiyas contributions to architecture are considered most impressive while Sathavahanas ruled Telangana region for about 400 years right from the 2nd century B.C. to beyond the 2nd century A.D. Among Kakathiyas, Prataparudra, was a great ruler who ruled till A.D.1323.During the rule of Bahamani, Quli Qutub, born in Persia, came to Deccan and he had become the Governor of this region. Quli Qutub later became independent and formed his own Qutubshahi Dynasty in 1518. The Golkonda fort was built by Quli qutub. In his reign, two tanks such as Ibrahim Pantam tank and Hussainsagar were built including a bridge on river Musi, which is known as Puranapul. The Hindus of Telangana region remember him for his immense patronage of Telugu literature. Many Telugu poets such as Addanki Gangadhar Kavi, Panuganti Telanganarya, Kandukuri Rudra Kavi had flourished in his court. Qutubshah then shifted the capital from Golkonda to Hyderabad on the banks of the river Musi. He built the Jamia mosque at Charminar. The State of Hyderabad was eventually founded by Mir Qamruddin Chin Qilich Khan. Later, he conferred himself the title of Asaf Jah, by which title the dynasty is still known. Telangana agitation was launched in 1969. Following subsequent Gentleman’s agreement and again a period of broken promises and injustice, Telangana movement was given a final push by Shri. K Chandrasekhar Rao in 2001 with the formation of TRS. Finally due to the whole hearted efforts of Telangana society and political parties, the Government of India agreed for creation of a separate Telangana in July, 2013 and Telangana came into effect on June 2, 2014 as ‘Telangana’, the 29th state of Indian Union "
 },
 
 {
    id: "IN-GA",
    layout:telangana,
    state_info:"Goa, the smallest state in India by area, is renowned for its stunning beaches, vibrant culture, and Portuguese heritage. Located on the western coast along the Arabian Sea, Goa spans an area of 3,702 square kilometers and is bordered by Maharashtra to the north, Karnataka to the east and south, and the Arabian Sea to the west. Panaji is the state capital, while Vasco da Gama is its largest city. Known as the Pearl of the Orient, Goa is a blend of scenic beauty, colonial architecture, and modern tourism, making it one of India's most popular destinations.Historically, Goa has been influenced by several dynasties, including the Mauryas, Satavahanas, and Chalukyas, before being annexed by the Portuguese in 1510. The Portuguese ruled Goa for over 450 years, leaving a lasting imprint on its culture, architecture, and cuisine. Goa was liberated from Portuguese control in 1961 and became the 25th state of India on May 30, 1987. The state’s unique blend of Indian and Portuguese traditions is evident in its festivals, language, and lifestyle.Tourism is the backbone of Goa's economy, attracting millions of domestic and international visitors annually. The state is famous for its pristine beaches like Calangute, Baga, Anjuna, and Palolem, as well as its vibrant nightlife and water sports. Goa’s historical sites, including the Basilica of Bom Jesus, a UNESCO World Heritage Site, and the forts of Aguada and Chapora, reflect its rich colonial past. The state also hosts vibrant festivals like Carnival and Shigmo, which showcase its diverse cultural heritage."
 },
 
 {
    id: "IN-CT",
    layout:chhattisgarh,
    state_info:"Chhattisgarh  is a landlocked state in Central India. It is the ninth largest state by area, and with a population of roughly 30 million, the seventeenth most populous.[13] It borders seven states – Uttar Pradesh to the north, Madhya Pradesh to the northwest, Maharashtra to the southwest, Jharkhand to the northeast, Odisha to the east, Andhra Pradesh and Telangana to the south.[14] Formerly a part of Madhya Pradesh, it was granted statehood on 1 November 2000 with Raipur as the designated state capital.[15]Chhattisgarh is one of the fastest-developing states in IndiageoghrapyThe northern and southern parts of the state are hilly, while the central part is a fertile plain. The highest point in the state is the Gaurlata near Samri, Balrampur-Ramanujganj district.[39] Deciduous forests of the Eastern Highlands Forests cover roughly 44% of the state.[40] In the north lies the edge of the great Indo-Gangetic plain. The Rihand River, a tributary of the Ganges, drains this area. The eastern end of the Satpura Range and the western edge of the Chota Nagpur Plateau form an east–west belt of hills that divide the Mahanadi River basin from the Indo-Gangetic plain. The outline of Chhattisgarh is like a sea horse.The central part of the state lies in the fertile upper basin of the Mahanadi and its tributaries, of which Shivnath River is a major one running around 300 km long. This area has extensive rice cultivation. The upper Mahanadi basin is separated from the upper Narmada basin to the west by the Maikal Hills (part of the Satpuras) and from the plains of Odisha to the east by ranges of hills. The southern part of the state lies on the Deccan plateau, in the watershed of the Godavari River and its tributary, the Indravati River. The Mahanadi is the chief river of the state. The other main rivers are Hasdeo (a tributary of Mahanadi), Rihand, Indravati, Jonk, Arpa and Shivnath.[41]"
 },
 
 {
    id: "IN-KA",
    layout:karnataka,
    state_info:"Karnataka , formerly Mysore, State, southwestern India. Area: 74,051 sq mi (191,791 sq km). Population: (2011) 61,130,704. Capital: Bangalore. Lying on the Arabian Sea, it is bordered by the states of Goa, Maharashtra, Andhra Pradesh, Tamil Nadu, and Kerala. Much of its territory is situated on the Karnataka Plateau, in the southern plateau region of the Indian subcontinent and in the hill region of the Western Ghats. The area was ruled by a series of Hindu dynasties before coming under British control in 1831. Mysore returned to native rule in 1881 as a princely state. Its name was changed to Karnataka (“Lofty Land”) in 1973. The majority of the population is engaged in agriculture. Rice and sugarcane are cultivated on the coastal plain, and coffee and tea are grown in the hill region. Dravidian languages, especially Kannada, are spoken by most of the population.Bangalore , City (pop., 2001: city, 4,301,326; metro. area, 5,701,446), capital of Karnataka state, southern India. It is a cultural meeting place for speakers of the Kannada, Telugu, and Tamil languages. Founded in the 16th century, it became a fief of the Indian ruler Hyder Ali c. 1760 but was later taken by the British. It was the headquarters of the British administration 1831–81, when it was restored to the raja of Mysore (now Karnataka). Today, it is one of India’s largest cities and an industrial and educational centre.The name Mysore—or Mysuru, which more accurately reflects the pronunciation in Kannada—is from the Sanskrit word for “buffalo town,” as Karnataka formerly was called. It derives from the destruction of the buffalo-demon Mahishasura by the goddess Chamunda. The prehistory of Mysore is embedded in legends that concern the struggle that took place in southern India between Aryan peoples, who invaded from the north, and the original Dravidian inhabitants; in legendary form this struggle is represented as a conflict between devils and demons on the one hand and gods and goddesses on the other. The documented history of the region focuses mostly on the princely state of Mysore as it existed before 1953, for no one dynasty succeeded in ruling the whole region occupied by the Kannada-speaking peoples—the area that essentially constitutes present-day Karnataka."
 },

 {
    id: 'IN-OR',
    layout:odisha,
    state_info:"Odisha, state of India. Located in the northeastern part of the country, it is bounded by the states of Jharkhand and West Bengal to the north and northeast, by the Bay of Bengal to the east, and by the states of Andhra Pradesh and Telangana to the south and Chhattisgarh to the west. Before India became independent in 1947, Odisha’s capital was at Cuttack. The present capitol was subsequently built at Bhubaneshwar, in the vicinity of the city’s historic temples in the east-central coastal plains. In late 2011 the state’s name was officially changed from Orissa to Odisha. Area 60,119 square miles (155,707 square km). Pop. (2011) 41,947,358HISTORY.Prehistoric Acheulian tools dating to Lower Paleolithic era have been discovered in various places in the region, implying an early settlement by humans. Kalinga has been mentioned in ancient texts like Mahabharata, Vayu Purana and Mahagovinda Suttanta. ccording to political scientist Sudama Misra, the Kalinga janapada originally comprised the area covered by the Puri and Ganjam districts.[38] The Sabar people of Odisha have also been mentioned in the Mahabharata.On 1 April 1936, Bihar and Orissa were split into separate provinces. The new province of Orissa came into existence on a linguistic basis during the British rule in India, with Sir John Austen Hubback as the first governor.[61][62] Following India's independence, on 15 August 1947, 27 princely states signed the document to join Orissa.[63] Most of the Orissa Tributary States, a group of princely states, acceded to Orissa in 1948, after the collapse of the Eastern States Union. Odisha has been divided into 30 districts. These 30 districts have been placed under three different revenue divisions to streamline their governance. The divisions are North, Central and South, with their headquarters at Sambalpur, Cuttack and Berhampur respectively. Each division consists of ten districts and has as its administrative head a Revenue Divisional Commissioner (RDC). The position of the RDC in the administrative hierarchy is that between that of the district administration and the state secretariat. The RDCs report to the Board of Revenue, which is headed by a senior officer of the Indian Administrative Service."
 },

 {
    id: 'IN-DN',
    layout:Dadra,
    state_info:"Dadra and Nagar Haveli is a Union Territory located on the western coast of India, bordered by Gujarat to the north and Maharashtra to the south. The territory spans an area of 491 square kilometers and is made up of two distinct regions: Dadra, a small enclave near Vapi in Gujarat, and Nagar Haveli, a larger area that lies between Gujarat and Maharashtra. The Union Territory has a rich history, having been ruled by various dynasties, including the Marathas, before being annexed by the Portuguese in the 18th century. It remained under Portuguese control until it was liberated by Indian forces in 1954, becoming part of India. In 2020, Dadra and Nagar Haveli merged with Daman and Diu to form a single Union Territory.The culture of Dadra and Nagar Haveli is a blend of Indian and Portuguese influences, evident in its architecture, cuisine, and festivals. The majority of the population speaks Marathi, Hindi, and Gujarati, reflecting the influence of neighboring states. The region is known for its vibrant festivals such as Diwali, Ganesh Chaturthi, and Christmas, which are celebrated with enthusiasm, along with regional events like the traditional harvest festival of Baisakhi. The territory’s cuisine combines flavors from both Gujarat and Maharashtra, with dishes like dhokla, fafda, and pattice being popular."
 },

 {
    id: "IN-MH",
    layout:maharashtra,
    state_info:"Maharashtra, located in the western region of India, is one of the country's most economically developed and culturally rich states. Spanning an area of 307,713 square kilometers, Maharashtra is the third-largest state in India and is bordered by Gujarat to the north, Madhya Pradesh to the east, Chhattisgarh to the southeast, Karnataka to the south, and the Arabian Sea to the west. Mumbai, the state capital, is not only the financial capital of India but also one of the world’s largest metropolitan areas, housing major industries, businesses, and a thriving entertainment hub, especially known for Bollywood, the Hindi film industry.Historically, Maharashtra has been home to various powerful dynasties such as the Mauryas, Satavahanas, Chalukyas, and the Marathas, with the Maratha Empire, under the leadership of Chhatrapati Shivaji Maharaj, playing a particularly important role in shaping the state’s identity. The state’s rich cultural heritage is reflected in its festivals, music, dance, and art forms. Festivals like Ganesh Chaturthi, Gudi Padwa, and Makar Sankranti are celebrated with immense fervor across the state. The state also has a deep-rooted tradition in literature, with Marathi being the primary language and a rich history of classical music, theater, and folk art.Maharashtra is one of India’s economic powerhouses, contributing significantly to the nation’s GDP. It is a hub for diverse industries, including finance, manufacturing, agriculture, and information technology. The state is home to the country’s financial capital, Mumbai, which hosts the Bombay Stock Exchange, major banks, and global corporate headquarters. The agriculture sector, though less dominant today, still plays an important role, with crops like sugarcane, rice, cotton, and fruits such as oranges and bananas being extensively grown. Maharashtra is also one of the largest producers of cotton and sugar in India."
 },

 {  id: 'IN-JH',
   layout:jharkhand,
   state_info:"Jharkhand, state of India, located in the northeastern part of the country. Jharkhand is bordered by the states of Bihar to the north, West Bengal to the east, Odisha to the south, Chhattisgarh to the west, and Uttar Pradesh to the northwest. Its capital is Ranchi.Jharkhand, one of India’s newest states, was carved out of the southern portion of Bihar in 2000. Statehood was the culmination of a long struggle carried on primarily by the Adivasis, or Scheduled Tribes (an official term applied primarily to indigenous communities that fall outside the predominant Indian caste hierarchy). Indian independence brought relatively little socioeconomic benefit to the people of the Jharkhand area, which led to widespread discontent with the Bihar administration, particularly among the tribal peoples. The tribal groups initiated a call for independence from Bihar, and in the 1980s they became militant in their demand. In the 1990s, the separation movement spread to nontribal communities, ultimately precipitating the creation of a new state. Area 28,833 square miles (74,677 square km). Pop. (2011) 32,966,238Prior to the arrival of the British in Chota Nagpur, the area was ruled by chiefs of various indigenous groups. The area came under the British in 1765 as part of Bihar. As the British gradually expanded their authority over the plains to the north of present-day Jharkhand during the second half of the 18th century and the beginning of the 19th, revolts against them occasionally erupted in Chota Nagpur. The most important of these uprisings were the Ho revolt (1820–27) and the Munda uprising (1831–32).From the period of British expansion until the turn of the 21st century, the history of Jharkhand overlapped with the history of Bihar. On Nov. 15, 2000, after decades of growing discontent, especially on the part of the indigenous peoples, Chota Nagpur was separated from Bihar to become Jharkhand, the 28th state of India"
 },

 {
    id: 'IN-BR',
    layout:bihar,
    state_info:"Bihar, located in the eastern part of India, is one of the country’s most historically significant states, with a rich cultural and political heritage. Spanning an area of 94,163 square kilometers, it is bordered by Nepal to the north, Uttar Pradesh to the west, Jharkhand to the south, and West Bengal to the east. The state is divided into 38 districts, with Patna, its capital and largest city, being a major cultural, political, and economic center. Bihar is known for its deep historical roots, as it was the heart of the ancient Maurya and Gupta empires, which made significant contributions to governance, science, and philosophy. The region is also closely associated with the development of Buddhism and Jainism, as it was the site of Lord Buddha's enlightenment in Bodh Gaya and the birthplace of Lord Mahavira in Vaishali.Bihar  is a state in Eastern India. It is the third largest state by population, the 12th largest by area, and the 15th largest by GDP in 2021. Bihar borders Uttar Pradesh to its west, Nepal to the north, the northern part of West Bengal to the east, and Jharkhand to the south. Bihar is split by the river Ganges, which flows from west to east.[4] On 15 November 2000, southern Bihar was ceded to form the new state of Jharkhand.[14] Only 11.27% of the population of Bihar lives in urban areas as per a 2020 report.[15] Additionally, almost 58% of Biharis are below the age of 25, giving Bihar the highest proportion of young people of any Indian state.[16] The official language is Hindi, which shares official status alongside that of Urdu. The main native languages are Maithili, Magahi and Bhojpuri. But there are several other languages being spoken at smaller levels.In Ancient and Classical India, the area that is now Bihar was considered the centre of political and cultural power and as a haven of learning. From Magadha arose India's first empire, the Maurya empire, as well as one of the world's most widely adhered-to religions: Buddhism. Magadha empires, notably under the Maurya and Gupta dynasties, unified large parts of South Asia under a central rule.[19] Another region of Bihar, Mithila, was an early centre of learning and the centre of the Videha kingdom"
 },

 {
    id: 'IN-MP',
    layout:madhya,
    state_info:"History of Madhya Pradesh, India is rich and diverse, with a legacy that spans thousands of years. It can be divided into three different stages as ancient, medieval and modern periods.  Madhya Pradesh has a rich and ancient history that dates back to the prehistoric era. The region was inhabited by early humans as early as 300,000 years ago. Evidence of this early habitation can be found in the form of rock paintings, stone tools, and other artifacts. Some of the rock paintings, stone and metal shows around the rivers, valleys, and other areas of Madhya Pradesh indicate that the area has been inhabited since prehistoric times.The region was once home to extensive empires of the Mauryas, Guptas, and Harsha. The medieval period saw the dominance of Rajput's, Mughals, Marathas, and later the British. The Mughals established their firm control over this vast region. Following which Marathas were able to push back the Muslim invaders to extend their supremacy to areas in and around Avanti mahajanapada. The history and culture of Madhya Pradesh are deeply embedded in the magnanimous monuments and sites that spread far and wide across the state. They are the testament to the rich historical legacy and cultural fabric this enchanting place holds.Ancient Period•	Ancient Period:•	The region of Madhya Pradesh has a deep historical connection dating back to ancient times. It was part of various ancient empires and kingdoms, including the Mauryan and Gupta empires.•	The UNESCO-listed Sanchi Stupa, built during the reign of Emperor Ashoka in the 3rd century BCE, is one of the most significant Buddhist monuments in India.•	The Bhimbetka Rock Shelters is another must-visit historical site. Recognized by UNESCO, these ancient rock shelters display the early traces of human life on the Indian Subcontinent, taking us back to Prehistoric times. These caves show us the evidence of Paleolithic settlements in the state of Madhya Pradesh. Some of the painted pottery•	During the Vedic period (1500-500 BCE), Madhya Pradesh was part of the Avanti kingdom. The Avanti kingdom was one of the most powerful kingdoms in India at the time. It was known for its trade and commerce, as well as its cultural and intellectual achievements. Later Avanti was annexed by Shishunaga into the Magadha Empire. Later the Shishunaga dynasty was overthrown by the Nanda's who were later replaced by the Mauryan."
 },

 {
   id: 'IN-UP',
   layout:uttar,
   state_info:"Uttar Pradesh  is a state in northern India. With over 241 million inhabitants, it is the most populated state in India as well as the most populous country subdivision in the world – more populous than all but four other countries outside of India (China, United States, Indonesia, and Pakistan) – and accounting for 16.5 per cent of the population of India or around 3 per cent of the total world population. The state is bordered by Rajasthan to the west, Haryana, Himachal Pradesh and Delhi to the orthwest, Uttarakhand and Nepal to the north, Bihar to the east, Madhya Pradesh, Chhattisgarh and Jharkhand to the south. It is the fourth-largest Indian state by area covering 243,286 km2 (93,933 sq mi), equal to 7.3 per cent of the total area of India. Lucknow serves as the state capital, with Prayagraj being the judicial capital. It is divided into 18 divisions and 75 districts. On 9 November 2000, a new state, Uttaranchal (now Uttarakhand), was created from Uttar Pradesh's western Himalayan hill region. The two major rivers of the state, the Ganges and its tributary Yamuna, meet at the Triveni Sangam in Prayagraj, a Hindu pilgrimage site. Other notable rivers are Gomti and Saryu. The forest cover in the state is 6.1 per cent of the state's geographical area. The cultivable area is 82 per cent of the total geographical area, and the net area sown is 68.5 per cent of the cultivable area.  Uttar Pradesh was established in 1950 after India had become a republic. It is a successor to the United Provinces, established in 1935 by renaming the United Provinces of Agra and Oudh, in turn established in 1902 from the North-Western Provinces and the Oudh Province. Though long known for sugar production, the state's economy is now dominated by the services industry. The service sector comprises travel and tourism, hotel industry, real estate, insurance and financial consultancies. The economy of Uttar Pradesh is the third-largest state economy in India, with ₹18.63 lakh crore (US$220 billion) in gross domestic product and a per capita GSDP of ₹68,810 (US$820). The High Court of the state is located in Prayagraj. The state contributes 80 seats to the lower house Lok Sabha and 31 seats and the upper house Rajya Sabha. Inhabitants of the state are called Awadhi, Bagheli, Bhojpuriya, Braji, Bundeli, Kannauji or Rohilkhandi depending upon their region of origin. Hinduism is practised by more than three-fourths of the population, with Islam being the next-largest religious group. Hindi is the most widely spoken language and is also the official language of the state, along with Urdu."
 },

 {
    id: 'IN-GJ',
    layout:Gujarat,
    state_info:"Gujarat, located on the western coast of India, is a vibrant state known for its rich cultural heritage, industrial prowess, and historical significance. Covering an area of 196,024 square kilometers, it is bordered by Rajasthan to the north, Maharashtra to the south, Madhya Pradesh to the east, and the Arabian Sea to the west. The state also shares an international border with Pakistan. Gandhinagar, the state capital, and Ahmedabad, its largest city, are important economic and cultural hubs. Gujarat is renowned for its long coastline, which stretches over 1,600 kilometers, making it a crucial center for maritime trade.he history of Gujarat is deeply rooted in ancient Indian civilization, with the region being a prominent part of the Indus Valley Civilization. Sites like Lothal and Dholavira highlight its role in early trade and urban planning. Over the centuries, Gujarat was ruled by various dynasties, including the Mauryas, Guptas, Chalukyas, and the Mughals, before becoming a part of the British Indian Empire. It played a pivotal role in India’s freedom struggle, with Mahatma Gandhi, the Father of the Nation, hailing from this land. Post-independence, Gujarat was carved out as a separate state from the Bombay State on May 1, 1960.Culturally, Gujarat is a mosaic of traditions, festivals, and art forms. The state is famous for its vibrant Navratri celebrations, marked by the energetic Garba and Dandiya Raas dances. Other significant festivals include Uttarayan, the International Kite Festival, and the Rann Utsav, a cultural extravaganza in the white deserts of Kutch. Gujarati cuisine, characterized by its unique blend of sweet, spicy, and tangy flavors, includes dishes like dhokla, thepla, khandvi, and fafda. The state is also known for its textile heritage, with traditional crafts such as bandhani, patola silk, and block printing gaining global recognition."
 },

 {
    id: 'IN-DD',
    layout:nagaland,
    state_info:"Daman and Diu, located along India’s western coast, are two distinct regions with a combined area of 112 square kilometers, known for their rich Portuguese heritage and natural beauty. Separated by approximately 650 kilometers, Daman lies on the Gujarat coast, while Diu is an island off Gujarat’s southern coast connected by a causeway. The regions enjoy a tropical climate with warm summers, mild winters, and monsoon rains. Historically, Daman and Diu were part of the Portuguese colonial empire for over 450 years, serving as significant trading and naval hubs. Diu’s strategic importance as a naval base and Daman’s fortified settlements highlight their historical relevance. Both regions were liberated in 1961 during Operation Vijay and became part of India. Initially grouped with Goa as a Union Territory, they were designated as a separate Union Territory in 1987 after Goa attained statehood and later merged with Dadra and Nagar Haveli in 2020.The culture of Daman and Diu reflects a harmonious blend of Indian and Portuguese traditions. Gujarati is the most widely spoken language, while Hindi and English are also prevalent. The Portuguese legacy is visible in the architecture, festivals, and cuisine, though the language itself is now rarely spoken. Hinduism, Christianity, and Islam are the major religions, with Christian celebrations like Christmas and Easter showcasing the colonial influence alongside traditional Indian festivals such as Diwali, Navratri, and Holi. Economically, Daman and Diu thrive on fishing, tourism, and industry. Daman is an industrial hub with thriving textile, plastic, and chemical industries due to favorable tax policies, while Diu’s economy benefits from fishing and its growing reputation as a tourist destination."
 },
 
 {
    id: 'IN-RJ',
    layout:rajasthan,
    state_info:"Rajasthan means  land of king is a northeastern state of India.  It is the largest Indian state by area and the seventh largest by population. It is on India's northwestern side, where it comprises most of the wide and inhospitable Thar Desert (also known as the Great Indian Desert) and shares a border with the Pakistani provinces of Punjab to the northwest and Sindh to the west, along the SutlejIndus River valley. It covers 342,239 square kilometres (132,139 sq mi) or 10.4 per cent of India's total geographical area.  The capital of Rajasthan is Jaipur. Its major features include the ruins of the Indus Valley civilisation at Kalibangan and Balathal, the Dilwara Temples, a Jain pilgrimage site at Rajasthan's only hill station, Mount Abu, in the ancient Aravalli mountain range and eastern Rajasthan, the Keoladeo National Park of Bharatpur, a World Heritage Site known for its bird life. Rajasthan is also home to three      national tiger reserves, the Ranthambore National Park in Sawai Madhopur, Sariska Tiger Reserve in Alwar and the Mukundra Hills Tiger Reserve in Kota. Its geographical location is 23°.3' to 30°.12' North latitude and 69°.30' to 78°.17' East longitude, with the Tropic of Cancer passing through its southernmost tip.HISTORY The history of Rajasthan begins from prehistoric times. The culture of the  was similar to the Indus Valley Civilization between 3000 and 1000 BC. Gujjars, also known as Gurjar, Goojar, or Gojar, ruled most of Rajasthan until the 12th century. Most parts of Gujarat and Rajasthan were known as 'Gurjatra,' i.e., 'Gujjar-protected areas.' Gurjara-Pratiharas had saved entire northern India from Arab invasions for 300 years. Later, Rajputs took suzerainty over various parts of this state, and those areas known as 'Rajputana,' i.e., 'place of Rajputs' in the British period. Rajasthan was ruled by many great Rajput rulers such as Bappa Rawal, Rana Kumbha, Rana Sanga, and Rana Pratap. Mewar was the most prominent and powerful state of Rajasthan in the medieval period."
 },
 
 { id: 'IN-DL',
   layout:delhi,
   state_info:"Delhi, the capital of India, is a vibrant metropolis steeped in history and pulsating with modernity. Located in the northern part of the country, Delhi spans an area of 1,484 square kilometers and serves as both a city and a Union Territory. It is bordered by Haryana on three sides and Uttar Pradesh to the east, with the Yamuna River flowing through it. Delhi is a unique blend of ancient heritage and contemporary urban development, hosting iconic landmarks alongside a rapidly evolving skyline. The city has two distinct parts: Old Delhi, known for its historical charm, narrow lanes, and bustling bazaars, and New Delhi, the seat of India’s government, characterized by wide avenues, colonial architecture, and modern infrastructure.The history of Delhi spans several millennia, with its roots going back to the ancient city of Indraprastha, mentioned in the Mahabharata. Over the centuries, it has been the capital of several empires, including the Delhi Sultanate and the Mughal Empire, which left behind grand monuments such as the Red Fort, Jama Masjid, and Humayun’s Tomb. The city witnessed significant historical events, including the rise of the British Raj, the freedom movement, and its designation as the national capital in 1911. Post-independence, Delhi became the political and administrative heart of India, housing landmarks like the Rashtrapati Bhavan, Parliament House, and India Gate."
 },
 
 {id: 'IN-HR',
   layout:haryana,
   state_info:"Haryana as a state came into existence on 1 November 1966 the Punjab Reorganisation Act (1966). The Indian government set up the Shah Commission under the chairmanship of Justice JC Shah on 23 April 1966 to divide the existing state of Punjab and determine the boundaries of the new state of Haryana after consideration of the languages spoken by the people. It encompassed the predominantly Hindi-speaking southern part of former Punjab, while the state of Punjab was reduced to the area where Punjabi speakers formed the majority population. The commission delivered its report on 31 May 1966 whereby the then-districts of Hisar, Mahendragarh, Gurgaon, Rohtak and Karnal were to be a part of the new state of Haryana. Further, the tehsils of Jind and Narwana in the Sangrur district – along with Naraingarh, Ambala and Jagadhri – were to be included.[27]The commission recommended that the tehsil of Kharar, which includes Chandigarh, the state capital of Punjab, should be a part of Haryana. However, Kharar was given to Punjab.[28] The city of Chandigarh was made a union territory, serving as the capital of both Punjab and Haryana.[29]hagwat Dayal Sharma became the first Chief Minister of Haryana.[30] Chaudhary Devi Lal is credited to be the individual who pushed for the creation of this commission. He was an instrumental figure in the separation of the Haryana state from Punjab in 1966.[31]The Vedas, the most ancient manuscripts of the Vedic religion, stem from the area that is now known as Haryana. These Sanskrit documents were written by the Aryans, who descended into the region from the north between 2000 and 1500 bce. Haryana is also considered to be the birthplace of Hinduism, which began to take discernible shape by the 2nd century bce and had developed two distinct branches by the 4th century "
 },

 {id: 'IN-UT',
   layout:uttarakhand,
  state_info:"Uttar Pradesh (/ˌʊtər prəˈdɛʃ/ UUT-ər prə-DESH; Hindi: [ˈʊtːəɾ pɾəˈdeːʃ]; lit. 'North Province') is a state in northern India. With over 241 million inhabitants, it is the most populated state in India as well as the most populous country subdivision in the world – more populous than all but four other countries outside of India (China, United States, Indonesia, and Pakistan) – and accounting for 16.5 per cent of the population of India or around 3 per cent of the total world population. The state is bordered by Rajasthan to the west, Haryana, Himachal Pradesh and Delhi to the northwest, Uttarakhand and Nepal to the north, Bihar to the east, Madhya Pradesh, Chhattisgarh and Jharkhand to the south. It is the fourth-largest Indian state by area covering 243,286 km2 (93,933 sq mi), equal to 7.3 per cent of the total area of India. Lucknow serves as the state capital, with Prayagraj being the judicial capital. It is divided into 18 divisions and 75 districts. On 9 November 2000, a new state, Uttaranchal (now Uttarakhand), was created from Uttar Pradesh's western Himalayan hill region. The two major rivers of the state, the Ganges and its tributary Yamuna, meet at the Triveni Sangam in Prayagraj, a Hindu pilgrimage site. Other notable rivers are Gomti and Saryu. The forest cover in the state is 6.1 per cent of the state's geographical area. The cultivable area is 82 per cent of the total geographical area, and the net area sown is 68.5 per cent of the cultivable area.  Uttar Pradesh was established in 1950 after India had become a republic. It is a successor to the United Provinces, established in 1935 by renaming the United Provinces of Agra and Oudh, in turn established in 1902 from the North-Western Provinces and the Oudh Province. Though long known for sugar production, the state's economy is now dominated by the services industry. The service sector comprises travel and tourism, hotel industry, real estate, insurance and financial consultancies. The economy of Uttar Pradesh is the third-largest state economy in India, with ₹18.63 lakh crore (US$220 billion) in gross domestic product and a per capita GSDP of ₹68,810 (US$820). The High Court of the state is located in Prayagraj. The state contributes 80 seats to the lower house Lok Sabha and 31 seats and the upper house Rajya Sabha."
  
 },

 {id: 'IN-PB',
   layout:punjab,
   state_info:"Punjab is a state in northwestern India. Forming part of the larger Punjab region of the Indian subcontinent, the state is bordered by the Indian states of Himachal Pradesh to the north and northeast, Haryana to the south and southeast, and Rajasthan to the southwest; by the Indian union territories of Chandigarh to the east and Jammu and Kashmir to the north. It shares an international border with Punjab, a province of Pakistan to the west. The state covers an area of 50,362 square kilometres (19,445 square miles), which is 1.53% of India's total geographical area,[10] making it the 19th-largest Indian state by area out of 28 Indian states (20th largest, if Union Territories are considered). With over 27 million inhabitants, Punjab is the 16th-largest Indian state by population, comprising 23 districts. Punjabi, written in the Gurmukhi script, is the most widely spoken and the official languageof the state.[11] The main ethnic group are the Punjabis, with Sikhs (57.7%) and Hindus (38.5%) forming the dominant religious groups. The state capital, Chandigarh, is a union territory and also the capital of the neighbouring state of Haryana. Three tributaries of the Indus River — the Sutlej, Beas, and Ravi — flow through Punjab.  HISTORY The History of Punjab refers to the past history of Punjab region which is a geopolitical, cultural, and historical region in the northwest of South Asia, comprising eastern Punjab province in Pakistan and western Punjab state in India. It is believed that the earliest evidence of human habitation in Punjab traces to the Soan valley of the Pothohar, between the Indus and the Jhelum rivers, where Soanian culture developed between 774,000 BC and 11,700 BC. This period goes back to the first interglacial period in the second Ice Age, from which remnants of stone and flint tools have been found.[2] The Punjab region was the site of one of the earliest cradle of civilizations, the Bronze Age Harrapan civilization that flourished from about 3000 B.C. and declined rapidly 1,000 years later, following the Indo-Aryan migrations that overran the region in waves between 1500 and 500 B.C."
   
  },

  {id: 'IN-HP',
   layout:himachal,
   state_info:"Himachal Pradesh, located in the northern part of India, is a land of breathtaking landscapes, snow-capped mountains, lush valleys, and vibrant cultural heritage. Spanning an area of 55,670 square kilometers, the state is bordered by Jammu and Kashmir to the north, Punjab to the west, Haryana to the southwest, and Uttarakhand to the southeast. It is also home to a significant part of the Western Himalayas, with its varied topography ranging from deep valleys to steep hills. The capital of Himachal Pradesh is Shimla, a popular hill station that served as the summer capital of British India. Other major cities include Manali, Dharamshala, and Kullu, which are renowned for their scenic beauty and tourism appeal Himachal Pradesh has a rich history, with influences from various ancient civilizations, including Buddhist, Hindu, and Tibetan cultures. The region has been a significant part of Indian history, and many dynasties have ruled over it, leaving behind a wealth of historical and religious sites. The state is famous for its temples, monasteries, and forts, with places like the Kangra Fort, Chamba Valley, and the ancient temples of Baijnath and Jwalamukhi attracting pilgrims and history enthusiasts alike. Dharamshala, home to the Tibetan Government-in-Exile and the Dalai Lama, is an important center for Tibetan culture and Buddhism.Himachal Pradesh is also known for its handicrafts, including woolen shawls, carpets, and Pashmina wool, which reflect the state’s artistic traditions. The local cuisine, influenced by both Tibetan and Punjabi styles, includes dishes like chana madra, sidu, and the famous Himachali apple cider. The state’s tourism, agriculture, and handicrafts have contributed to its growing economy."
  
},

 {
    id: 'IN-JK',
    layout:jm,
    state_info:"Jammu and Kashmir, located in the northernmost part of India, is a region of unparalleled natural beauty, rich history, and cultural diversity. It is bordered by Himachal Pradesh and Punjab to the south, Pakistan to the west, and China to the north and east. Covering an area of 55,673 square kilometers (post the bifurcation of Ladakh in 2019), Jammu and Kashmir is a Union Territory comprising two distinct regions: Jammu, known for its temples and vibrant culture, and Kashmir, celebrated for its breathtaking landscapes, serene lakes, and snow-capped mountains. The region is traversed by the mighty Himalayas and the Pir Panjal ranges, with the Jhelum River being a lifeline for the Kashmir Valley.The history of Jammu and Kashmir is marked by its strategic location on the Silk Route, making it a melting pot of various cultures and religions over centuries. The region has seen the influence of Hinduism, Buddhism, and Islam, as well as Persian and Central Asian cultures. In 1846, it became a princely state under the Dogra rule, and following India's independence in 1947, it acceded to India under specific conditions, granting it a special status under Article 370 of the Indian Constitution. However, in August 2019, Article 370 was abrogated, and Jammu and Kashmir was reorganized into a Union Territory, while Ladakh was carved out as a separate Union Territory.Culturally, Jammu and Kashmir are distinct yet interconnected. Jammu is often referred to as the City of Temples, with the Vaishno Devi shrine being one of the most visited pilgrimage sites in India."
 },
 
 {
    id: 'IN-CH',
    layout:chandigarh,
    state_info:"Chandigarh, the capital of both Haryana and Punjab, is one of India’s most well-planned cities, renowned for its modern architecture, green spaces, and high standard of living. Located at the foothills of the Shivalik range, it is the first city in India to be designed and developed as a modern, independent urban center post-independence. Spread over an area of 114 square kilometers, Chandigarh serves as a Union Territory, directly governed by the President of India. The city is famous for its orderly layout, with distinct sectors and wide avenues, offering a contrast to the chaotic nature of many other Indian cities.Designed by the famous French architect Le Corbusier, Chandigarh stands out for its innovative urban planning and architecture. The city is divided into 47 sectors, each serving as self-contained neighborhoods with schools, parks, and commercial areas, contributing to a sense of organization and efficiency. Iconic landmarks like the Capitol Complex, the Rock Garden, and Sukhna Lake reflect the city’s modernistic spirit and aesthetic appeal. The Rock Garden, created by Nek Chand from discarded materials, has become a symbol of creativity, while Sukhna Lake, a man-made reservoir, is a popular spot for leisure and recreation."
 },
 
 
];

export default stateInfo;